services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=requalify'
      - 'POSTGRES_PASSWORD=requalify'
      - 'POSTGRES_USER=requalify'
    ports:
      - '5433:5432'

  rabbitmq:
    image: 'rabbitmq:4.0-management'
    container_name: 'rabbitmq'
    restart: 'unless-stopped'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest