services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=requalify'
      - 'POSTGRES_PASSWORD=requalify'
      - 'POSTGRES_USER=requalify'
    ports:
      - '5433:5432'
